import {
  User,
  Property,
  ActionItem,
  StocktakeItem,
  StocktakeEntry,
  Booking,
  PreCheckIn,
  PostCheckOut,
  WeeklyCheck,
  MonthlyCheck,
  Approval,
  WorkTicket,
} from '../types';

export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    name: 'Sarah Johnson',
    email: 'sarah@retreats.com',
    role: 'admin',
    propertyIds: ['p1', 'p2', 'p3', 'p4', 'p5'],
    phone: '07700 900001',
    active: true,
    createdAt: '2023-01-15T09:00:00Z',
  },
  {
    id: 'u2',
    name: 'James Hartley',
    email: 'james@retreats.com',
    role: 'manager',
    propertyIds: ['p1', 'p2', 'p3'],
    phone: '07700 900002',
    active: true,
    createdAt: '2023-02-01T09:00:00Z',
  },
  {
    id: 'u3',
    name: 'Emily Clarke',
    email: 'emily@retreats.com',
    role: 'caretaker',
    propertyIds: ['p1', 'p2'],
    phone: '07700 900003',
    active: true,
    createdAt: '2023-03-10T09:00:00Z',
  },
  {
    id: 'u4',
    name: 'Tom Briggs',
    email: 'tom@retreats.com',
    role: 'caretaker',
    propertyIds: ['p3', 'p4', 'p5'],
    phone: '07700 900004',
    active: true,
    createdAt: '2023-03-15T09:00:00Z',
  },
  {
    id: 'u5',
    name: 'Lisa Park',
    email: 'lisa@retreats.com',
    role: 'cleaner',
    propertyIds: ['p1', 'p2', 'p3'],
    phone: '07700 900005',
    active: true,
    createdAt: '2023-04-01T09:00:00Z',
  },
  {
    id: 'u6',
    name: 'Mike Turner',
    email: 'mike@retreats.com',
    role: 'cleaner',
    propertyIds: ['p4', 'p5'],
    phone: '07700 900006',
    active: false,
    createdAt: '2023-04-15T09:00:00Z',
  },
];

export const MOCK_PROPERTIES: Property[] = [
  {
    id: 'p1',
    name: 'The Old Barn',
    address: 'Meadow Lane, Chipping Norton, Oxfordshire, OX7 5SP',
    bedrooms: 5,
    maxGuests: 10,
    type: 'barn',
    active: true,
    notes: 'Grade II listed. Hot tub requires weekly chemical check.',
  },
  {
    id: 'p2',
    name: 'Lakeside Lodge',
    address: '14 Lakeview Drive, Windermere, Cumbria, LA23 1BB',
    bedrooms: 4,
    maxGuests: 8,
    type: 'lodge',
    active: true,
    notes: 'Boat house access included. Lake permits required for guests.',
  },
  {
    id: 'p3',
    name: 'Hilltop Cottage',
    address: 'Top Lane, Haworth, West Yorkshire, BD22 8RT',
    bedrooms: 3,
    maxGuests: 6,
    type: 'cottage',
    active: true,
    notes: 'Oil tank checks monthly. Steep driveway – advise guests.',
  },
  {
    id: 'p4',
    name: 'Coastal Villa',
    address: '7 Cliff Road, St Ives, Cornwall, TR26 2HQ',
    bedrooms: 6,
    maxGuests: 12,
    type: 'villa',
    active: true,
    notes: 'Sea-view decking. Salt air corrosion checks quarterly.',
  },
  {
    id: 'p5',
    name: 'Forest Retreat',
    address: 'Woodland Way, Betws-y-Coed, Conwy, LL24 0AJ',
    bedrooms: 4,
    maxGuests: 8,
    type: 'lodge',
    active: true,
    notes: 'Wood burner serviced annually. Log store kept stocked Oct-Mar.',
  },
];

const today = new Date();
const addDays = (d: Date, n: number) => {
  const r = new Date(d);
  r.setDate(r.getDate() + n);
  return r.toISOString().split('T')[0];
};

export const MOCK_ACTION_ITEMS: ActionItem[] = [
  {
    id: 'ai1',
    title: 'Gas Safety Certificate',
    description: 'Annual gas safety check due. Arrange Gas Safe registered engineer.',
    propertyId: 'p1',
    dueDate: addDays(today, -5),
    category: 'safety',
    priority: 'critical',
    status: 'overdue',
    assignedTo: 'u2',
    approvalRequired: true,
    approvalStatus: 'pending',
    createdAt: '2025-01-01T09:00:00Z',
    updatedAt: '2025-03-01T09:00:00Z',
  },
  {
    id: 'ai2',
    title: 'PAT Testing – All Properties',
    description: 'Portable appliance testing for all electrical items.',
    propertyId: null,
    dueDate: addDays(today, 12),
    category: 'compliance',
    priority: 'high',
    status: 'in_progress',
    assignedTo: 'u3',
    approvalRequired: false,
    createdAt: '2025-01-15T09:00:00Z',
    updatedAt: '2025-03-10T09:00:00Z',
  },
  {
    id: 'ai3',
    title: 'Fire Extinguisher Service',
    description: 'Annual service of all fire extinguishers across properties.',
    propertyId: 'p2',
    dueDate: addDays(today, 3),
    category: 'safety',
    priority: 'high',
    status: 'pending',
    assignedTo: 'u4',
    approvalRequired: false,
    createdAt: '2025-02-01T09:00:00Z',
    updatedAt: '2025-03-15T09:00:00Z',
  },
  {
    id: 'ai4',
    title: 'EICR Electrical Inspection',
    description: '5-year electrical installation condition report for Hilltop Cottage.',
    propertyId: 'p3',
    dueDate: addDays(today, 45),
    category: 'compliance',
    priority: 'medium',
    status: 'pending',
    assignedTo: 'u2',
    approvalRequired: true,
    approvalStatus: 'approved',
    createdAt: '2025-02-15T09:00:00Z',
    updatedAt: '2025-03-20T09:00:00Z',
  },
  {
    id: 'ai5',
    title: 'Hot Tub Chemical Balance',
    description: 'Check and adjust pH, chlorine, and alkalinity levels.',
    propertyId: 'p1',
    dueDate: addDays(today, 0),
    category: 'maintenance',
    priority: 'high',
    status: 'pending',
    assignedTo: 'u3',
    approvalRequired: false,
    createdAt: '2025-03-01T09:00:00Z',
    updatedAt: '2025-03-25T09:00:00Z',
  },
  {
    id: 'ai6',
    title: 'Legionella Risk Assessment',
    description: 'Annual legionella risk assessment for all water systems.',
    propertyId: null,
    dueDate: addDays(today, 90),
    category: 'compliance',
    priority: 'high',
    status: 'pending',
    assignedTo: 'u2',
    approvalRequired: true,
    approvalStatus: 'pending',
    createdAt: '2025-03-01T09:00:00Z',
    updatedAt: '2025-03-25T09:00:00Z',
  },
  {
    id: 'ai7',
    title: 'Oil Tank Inspection',
    description: 'Check oil level and inspect tank for leaks or corrosion.',
    propertyId: 'p3',
    dueDate: addDays(today, 7),
    category: 'maintenance',
    priority: 'medium',
    status: 'pending',
    assignedTo: 'u4',
    approvalRequired: false,
    createdAt: '2025-03-10T09:00:00Z',
    updatedAt: '2025-03-25T09:00:00Z',
  },
  {
    id: 'ai8',
    title: 'Inventory Update – Coastal Villa',
    description: 'Full inventory check and update after recent refurb.',
    propertyId: 'p4',
    dueDate: addDays(today, 20),
    category: 'admin',
    priority: 'low',
    status: 'completed',
    assignedTo: 'u3',
    completedAt: addDays(today, -2),
    completedBy: 'u3',
    approvalRequired: false,
    createdAt: '2025-03-05T09:00:00Z',
    updatedAt: addDays(today, -2),
  },
];

export const MOCK_STOCKTAKE_ITEMS: StocktakeItem[] = [
  { id: 'si1', name: 'Toilet Rolls (pack of 9)', category: 'shelf', unit: 'packs', minStock: 2 },
  { id: 'si2', name: 'Kitchen Towels', category: 'shelf', unit: 'rolls', minStock: 4 },
  { id: 'si3', name: 'Bin Bags (30L)', category: 'shelf', unit: 'boxes', minStock: 1 },
  { id: 'si4', name: 'Dishwasher Tablets', category: 'shelf', unit: 'boxes', minStock: 1 },
  { id: 'si5', name: 'Washing Up Liquid', category: 'shelf', unit: 'bottles', minStock: 2 },
  { id: 'si6', name: 'Salt & Pepper (refills)', category: 'shelf', unit: 'sets', minStock: 2 },
  { id: 'si7', name: 'Tea / Coffee / Sugar', category: 'shelf', unit: 'sets', minStock: 1 },
  { id: 'si8', name: 'Washing Machine Pods', category: 'shelf', unit: 'packs', minStock: 1 },
  { id: 'si9', name: 'Bleach (750ml)', category: 'cleaning', unit: 'bottles', minStock: 3 },
  { id: 'si10', name: 'Bathroom Cleaner', category: 'cleaning', unit: 'bottles', minStock: 2 },
  { id: 'si11', name: 'Kitchen Degreaser', category: 'cleaning', unit: 'bottles', minStock: 2 },
  { id: 'si12', name: 'Floor Cleaner (5L)', category: 'cleaning', unit: 'bottles', minStock: 1 },
  { id: 'si13', name: 'Microfibre Cloths', category: 'cleaning', unit: 'packs', minStock: 2 },
  { id: 'si14', name: 'Mop Heads', category: 'cleaning', unit: 'units', minStock: 2 },
  { id: 'si15', name: 'Rubber Gloves (M)', category: 'cleaning', unit: 'pairs', minStock: 4 },
  { id: 'si16', name: 'Limescale Remover', category: 'cleaning', unit: 'bottles', minStock: 2 },
];

export const MOCK_STOCKTAKE_ENTRIES: StocktakeEntry[] = [
  {
    id: 'se1',
    propertyId: 'p1',
    date: addDays(today, -7),
    submittedBy: 'u3',
    items: [
      { itemId: 'si1', quantity: 3 },
      { itemId: 'si2', quantity: 5 },
      { itemId: 'si3', quantity: 2 },
      { itemId: 'si4', quantity: 2 },
      { itemId: 'si9', quantity: 4 },
      { itemId: 'si10', quantity: 3 },
    ],
    status: 'submitted',
  },
  {
    id: 'se2',
    propertyId: 'p2',
    date: addDays(today, -3),
    submittedBy: 'u3',
    items: [
      { itemId: 'si1', quantity: 1 },
      { itemId: 'si2', quantity: 2 },
      { itemId: 'si9', quantity: 1 },
    ],
    status: 'submitted',
    notes: 'Running low on toilet rolls – order needed.',
  },
];

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'b1',
    bookingRef: 'BK-2026-0401',
    guestName: 'Thompson Family',
    guestEmail: 'david.thompson@email.com',
    guestPhone: '07800 123456',
    propertyId: 'p1',
    checkIn: addDays(today, 0),
    checkOut: addDays(today, 7),
    guests: 8,
    status: 'confirmed',
    source: 'direct',
    notes: 'Anniversary celebration. Late arrival ~10pm.',
  },
  {
    id: 'b2',
    bookingRef: 'BK-2026-0402',
    guestName: 'Williams Party',
    guestEmail: 'j.williams@email.com',
    guestPhone: '07800 234567',
    propertyId: 'p2',
    checkIn: addDays(today, 0),
    checkOut: addDays(today, 4),
    guests: 6,
    status: 'checked_in',
    source: 'airbnb',
  },
  {
    id: 'b3',
    bookingRef: 'BK-2026-0403',
    guestName: 'Henderson Group',
    guestEmail: 'helen.henderson@email.com',
    guestPhone: '07800 345678',
    propertyId: 'p3',
    checkIn: addDays(today, 1),
    checkOut: addDays(today, 5),
    guests: 4,
    status: 'confirmed',
    source: 'booking.com',
  },
  {
    id: 'b4',
    bookingRef: 'BK-2026-0404',
    guestName: 'Morrison Retreat',
    guestEmail: 'sarah.morrison@email.com',
    guestPhone: '07800 456789',
    propertyId: 'p4',
    checkIn: addDays(today, 1),
    checkOut: addDays(today, 8),
    guests: 10,
    status: 'confirmed',
    source: 'vrbo',
    notes: 'Hen party – event venue in area.',
  },
  {
    id: 'b5',
    bookingRef: 'BK-2026-0405',
    guestName: 'Davies Family',
    guestEmail: 'r.davies@email.com',
    guestPhone: '07800 567890',
    propertyId: 'p2',
    checkIn: addDays(today, -3),
    checkOut: addDays(today, 0),
    guests: 5,
    status: 'checked_out',
    source: 'airbnb',
  },
  {
    id: 'b6',
    bookingRef: 'BK-2026-0406',
    guestName: 'Price Family',
    guestEmail: 'n.price@email.com',
    guestPhone: '07800 678901',
    propertyId: 'p5',
    checkIn: addDays(today, -1),
    checkOut: addDays(today, 0),
    guests: 7,
    status: 'checked_out',
    source: 'direct',
  },
];

const buildPreCheckInChecklist = () => [
  { id: 'pc1', label: 'All rooms cleaned and inspected', checked: false },
  { id: 'pc2', label: 'Welcome pack in place', checked: false },
  { id: 'pc3', label: 'All appliances tested', checked: false },
  { id: 'pc4', label: 'Heating set to correct temperature', checked: false },
  { id: 'pc5', label: 'Beds made with fresh linen', checked: false },
  { id: 'pc6', label: 'Towels provided (1 per guest)', checked: false },
  { id: 'pc7', label: 'Hot tub / jacuzzi sanitised (if applicable)', checked: false },
  { id: 'pc8', label: 'Outdoor areas tidy and safe', checked: false },
  { id: 'pc9', label: 'Information folder updated', checked: false },
  { id: 'pc10', label: 'Keys / access codes confirmed', checked: false },
];

const buildPostCheckOutChecklist = () => [
  { id: 'pco1', label: 'All rooms inspected for damage', checked: false },
  { id: 'pco2', label: 'Inventory checked', checked: false },
  { id: 'pco3', label: 'Keys / access codes returned', checked: false },
  { id: 'pco4', label: 'Laundry stripped and bagged', checked: false },
  { id: 'pco5', label: 'Rubbish removed', checked: false },
  { id: 'pco6', label: 'Fridge cleared of guest items', checked: false },
  { id: 'pco7', label: 'Windows and doors locked', checked: false },
  { id: 'pco8', label: 'Meter readings taken', checked: false },
];

export const MOCK_PRE_CHECKINS: PreCheckIn[] = [
  {
    id: 'pci1',
    bookingId: 'b1',
    propertyId: 'p1',
    scheduledDate: addDays(today, 0),
    status: 'pending',
    checklist: buildPreCheckInChecklist(),
    damageReported: false,
  },
  {
    id: 'pci2',
    bookingId: 'b3',
    propertyId: 'p3',
    scheduledDate: addDays(today, 1),
    status: 'pending',
    checklist: buildPreCheckInChecklist(),
    damageReported: false,
  },
  {
    id: 'pci3',
    bookingId: 'b4',
    propertyId: 'p4',
    scheduledDate: addDays(today, 1),
    status: 'pending',
    checklist: buildPreCheckInChecklist(),
    damageReported: false,
  },
  {
    id: 'pci4',
    bookingId: 'b2',
    propertyId: 'p2',
    scheduledDate: addDays(today, -3),
    completedAt: addDays(today, -3) + 'T11:30:00Z',
    completedBy: 'u3',
    status: 'completed',
    checklist: buildPreCheckInChecklist().map((i) => ({ ...i, checked: true })),
    damageReported: false,
  },
];

export const MOCK_POST_CHECKOUTS: PostCheckOut[] = [
  {
    id: 'poc1',
    bookingId: 'b5',
    propertyId: 'p2',
    scheduledDate: addDays(today, 0),
    status: 'pending',
    checklist: buildPostCheckOutChecklist(),
    damageReported: false,
    cleaningRequired: true,
  },
  {
    id: 'poc2',
    bookingId: 'b6',
    propertyId: 'p5',
    scheduledDate: addDays(today, 0),
    status: 'pending',
    checklist: buildPostCheckOutChecklist(),
    damageReported: false,
    cleaningRequired: true,
  },
  {
    id: 'poc3',
    bookingId: 'b2',
    propertyId: 'p2',
    scheduledDate: addDays(today, 4),
    status: 'pending',
    checklist: buildPostCheckOutChecklist(),
    damageReported: false,
    cleaningRequired: true,
  },
];

const buildWeeklyChecklist = () => [
  { id: 'wc1', label: 'Exterior lights working', checked: false },
  { id: 'wc2', label: 'Gutters clear of debris', checked: false },
  { id: 'wc3', label: 'Water pressure normal', checked: false },
  { id: 'wc4', label: 'Boiler / heating functional', checked: false },
  { id: 'wc5', label: 'Smoke & CO alarms tested', checked: false },
  { id: 'wc6', label: 'Hot tub / pool water quality check', checked: false },
  { id: 'wc7', label: 'Garden / outdoor maintenance', checked: false },
  { id: 'wc8', label: 'Car park / access clear', checked: false },
  { id: 'wc9', label: 'Emergency contacts board updated', checked: false },
  { id: 'wc10', label: 'Reported issues actioned', checked: false },
];

export const MOCK_WEEKLY_CHECKS: WeeklyCheck[] = [
  {
    id: 'wk1',
    propertyId: 'p1',
    weekStart: addDays(today, -7),
    completedAt: addDays(today, -5) + 'T09:00:00Z',
    completedBy: 'u3',
    status: 'completed',
    checklist: buildWeeklyChecklist().map((i) => ({ ...i, checked: true })),
    issuesFound: false,
  },
  {
    id: 'wk2',
    propertyId: 'p2',
    weekStart: addDays(today, 0),
    status: 'pending',
    checklist: buildWeeklyChecklist(),
    issuesFound: false,
  },
  {
    id: 'wk3',
    propertyId: 'p3',
    weekStart: addDays(today, 0),
    status: 'in_progress',
    checklist: buildWeeklyChecklist().map((i, idx) => ({ ...i, checked: idx < 5 })),
    issuesFound: true,
    notes: 'Water pressure slightly low – monitor.',
  },
  {
    id: 'wk4',
    propertyId: 'p4',
    weekStart: addDays(today, 0),
    status: 'pending',
    checklist: buildWeeklyChecklist(),
    issuesFound: false,
  },
  {
    id: 'wk5',
    propertyId: 'p5',
    weekStart: addDays(today, 0),
    status: 'pending',
    checklist: buildWeeklyChecklist(),
    issuesFound: false,
  },
];

const buildMonthlyChecklist = () => [
  { id: 'mc1', label: 'Electric meter reading taken', checked: false },
  { id: 'mc2', label: 'Gas meter reading taken', checked: false },
  { id: 'mc3', label: 'Water meter reading taken', checked: false },
  { id: 'mc4', label: 'Oil tank level checked', checked: false },
  { id: 'mc5', label: 'Septic tank level checked (if applicable)', checked: false },
  { id: 'mc6', label: 'Fire safety equipment inspected', checked: false },
  { id: 'mc7', label: 'First aid kit restocked', checked: false },
  { id: 'mc8', label: 'Deep clean of oven / appliances', checked: false },
  { id: 'mc9', label: 'Window cleaning', checked: false },
  { id: 'mc10', label: 'Inventory updated', checked: false },
  { id: 'mc11', label: 'Pest control check', checked: false },
  { id: 'mc12', label: 'Review guest feedback and address issues', checked: false },
];

export const MOCK_MONTHLY_CHECKS: MonthlyCheck[] = [
  {
    id: 'mck1',
    propertyId: 'p1',
    month: 'March',
    year: 2026,
    completedAt: '2026-03-28T10:00:00Z',
    completedBy: 'u3',
    status: 'completed',
    checklist: buildMonthlyChecklist().map((i) => ({ ...i, checked: true })),
    meterReadings: { electric: 14832, gas: 3241, water: 902 },
    notes: 'All good. Hot tub cover showing wear – order replacement.',
  },
  {
    id: 'mck2',
    propertyId: 'p2',
    month: 'April',
    year: 2026,
    status: 'pending',
    checklist: buildMonthlyChecklist(),
    meterReadings: {},
  },
  {
    id: 'mck3',
    propertyId: 'p3',
    month: 'April',
    year: 2026,
    status: 'in_progress',
    checklist: buildMonthlyChecklist().map((i, idx) => ({ ...i, checked: idx < 4 })),
    meterReadings: { electric: 8420, gas: 1102 },
  },
  {
    id: 'mck4',
    propertyId: 'p4',
    month: 'April',
    year: 2026,
    status: 'pending',
    checklist: buildMonthlyChecklist(),
    meterReadings: {},
  },
  {
    id: 'mck5',
    propertyId: 'p5',
    month: 'April',
    year: 2026,
    status: 'pending',
    checklist: buildMonthlyChecklist(),
    meterReadings: {},
  },
];

export const MOCK_APPROVALS: Approval[] = [
  {
    id: 'ap1',
    title: 'Hot Tub Cover Replacement',
    description: 'Existing cover cracked and no longer effective. New thermal cover required to maintain water temperature.',
    propertyId: 'p1',
    submittedBy: 'u3',
    submittedAt: '2026-03-28T14:00:00Z',
    amount: 385.0,
    category: 'maintenance',
    status: 'in_progress',
    history: [
      { id: 'ah1', action: 'submitted', by: 'u3', at: '2026-03-28T14:00:00Z', notes: 'Urgent – affects energy efficiency.' },
    ],
  },
  {
    id: 'ap2',
    title: 'Emergency Plumber – Lakeside Lodge',
    description: 'Burst pipe under kitchen sink. Emergency repair required before next guest arrival.',
    propertyId: 'p2',
    submittedBy: 'u4',
    submittedAt: '2026-03-30T08:30:00Z',
    amount: 220.0,
    category: 'emergency',
    status: 'approved',
    reviewedBy: 'u1',
    reviewedAt: '2026-03-30T09:15:00Z',
    reviewNotes: 'Approved – emergency spend. Keep receipt.',
    history: [
      { id: 'ah2', action: 'submitted', by: 'u4', at: '2026-03-30T08:30:00Z' },
      { id: 'ah3', action: 'approved', by: 'u1', at: '2026-03-30T09:15:00Z', notes: 'Approved – emergency spend. Keep receipt.' },
    ],
  },
  {
    id: 'ap3',
    title: 'Garden Furniture – Forest Retreat',
    description: 'Request to purchase 2x outdoor sofas and a fire pit table for the decking area.',
    propertyId: 'p5',
    submittedBy: 'u3',
    submittedAt: '2026-04-01T10:00:00Z',
    amount: 950.0,
    category: 'upgrade',
    status: 'in_progress',
    history: [
      { id: 'ah4', action: 'submitted', by: 'u3', at: '2026-04-01T10:00:00Z', notes: 'Quotes obtained from 2 suppliers.' },
    ],
  },
  {
    id: 'ap4',
    title: 'Cleaning Supplies Bulk Order',
    description: 'Monthly bulk order of cleaning products across all 5 properties.',
    propertyId: 'p1',
    submittedBy: 'u5',
    submittedAt: '2026-03-25T09:00:00Z',
    amount: 312.5,
    category: 'supplies',
    status: 'approved',
    reviewedBy: 'u2',
    reviewedAt: '2026-03-25T11:00:00Z',
    reviewNotes: 'Approved. Use regular supplier.',
    history: [
      { id: 'ah5', action: 'submitted', by: 'u5', at: '2026-03-25T09:00:00Z' },
      { id: 'ah6', action: 'approved', by: 'u2', at: '2026-03-25T11:00:00Z', notes: 'Approved. Use regular supplier.' },
    ],
  },
  {
    id: 'ap5',
    title: 'Smart Lock Installation – Coastal Villa',
    description: 'Replace 3 door locks with smart locks for keyless guest access.',
    propertyId: 'p4',
    submittedBy: 'u4',
    submittedAt: '2026-04-02T13:00:00Z',
    amount: 745.0,
    category: 'upgrade',
    status: 'rejected',
    reviewedBy: 'u1',
    reviewedAt: '2026-04-03T09:00:00Z',
    reviewNotes: 'Defer to next quarter. Budget constraints.',
    history: [
      { id: 'ah7', action: 'submitted', by: 'u4', at: '2026-04-02T13:00:00Z' },
      { id: 'ah8', action: 'rejected', by: 'u1', at: '2026-04-03T09:00:00Z', notes: 'Defer to next quarter. Budget constraints.' },
    ],
  },
];

export const MOCK_WORK_TICKETS: WorkTicket[] = [
  {
    id: 'wt1',
    title: 'Fix squeaky floorboard – Master Bedroom',
    description: 'Floorboard near window in master bedroom squeaks loudly. Guest complained.',
    propertyId: 'p1',
    assignedTo: 'u3',
    priority: 'medium',
    status: 'in_progress',
    category: 'repair',
    estimatedHours: 2,
    dueDate: addDays(today, 3),
    createdAt: '2026-03-28T09:00:00Z',
    updatedAt: '2026-03-30T09:00:00Z',
  },
  {
    id: 'wt2',
    title: 'Replace shower head – Bathroom 2',
    description: 'Shower head blocked and pressure reduced. Replace with new rainfall head.',
    propertyId: 'p2',
    assignedTo: 'u4',
    priority: 'high',
    status: 'open',
    category: 'maintenance',
    estimatedHours: 1,
    dueDate: addDays(today, 1),
    createdAt: '2026-04-01T10:00:00Z',
    updatedAt: '2026-04-01T10:00:00Z',
  },
  {
    id: 'wt3',
    title: 'Deep clean oven – Forest Retreat',
    description: 'Oven requires professional deep clean before next guests.',
    propertyId: 'p5',
    assignedTo: 'u5',
    priority: 'medium',
    status: 'completed',
    category: 'cleaning',
    estimatedHours: 3,
    actualHours: 2.5,
    completedAt: addDays(today, -1) + 'T15:00:00Z',
    createdAt: '2026-04-01T09:00:00Z',
    updatedAt: addDays(today, -1),
  },
  {
    id: 'wt4',
    title: 'Mow lawns – Hilltop Cottage',
    description: 'Weekly lawn maintenance. Front and rear gardens.',
    propertyId: 'p3',
    assignedTo: 'u4',
    priority: 'low',
    status: 'open',
    category: 'maintenance',
    estimatedHours: 2,
    dueDate: addDays(today, 5),
    createdAt: '2026-04-03T08:00:00Z',
    updatedAt: '2026-04-03T08:00:00Z',
  },
  {
    id: 'wt5',
    title: 'Repair garden gate latch – Coastal Villa',
    description: 'Gate latch broken – security issue. Fix or replace urgently.',
    propertyId: 'p4',
    assignedTo: 'u4',
    priority: 'urgent',
    status: 'open',
    category: 'repair',
    estimatedHours: 1,
    dueDate: addDays(today, 0),
    createdAt: '2026-04-04T07:00:00Z',
    updatedAt: '2026-04-04T07:00:00Z',
    notes: 'Guest reported this on checkout.',
  },
];
