/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    hotels: Hotel;
    rooms: Room;
    menus: Menu;
    events: Event;
    offers: Offer;
    pages: Page;
    media: Media;
    testimonials: Testimonial;
    enquiries: Enquiry;
    users: User;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    hotels: {
      rooms: 'rooms';
      menus: 'menus';
      events: 'events';
      offers: 'offers';
    };
  };
  collectionsSelect: {
    hotels: HotelsSelect<false> | HotelsSelect<true>;
    rooms: RoomsSelect<false> | RoomsSelect<true>;
    menus: MenusSelect<false> | MenusSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    offers: OffersSelect<false> | OffersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    'announcement-bar': AnnouncementBar;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'announcement-bar': AnnouncementBarSelect<false> | AnnouncementBarSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * One entry per property. The Overview tab is the hotel page itself.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hotels".
 */
export interface Hotel {
  id: number;
  name: string;
  /**
   * Keep this the same as the old website so Google links keep working.
   */
  slug?: string | null;
  /**
   * Short, e.g. "Hawkhurst, Kent"
   */
  location: string;
  /**
   * One line under the name, e.g. "Riverside coaching inn since 1545"
   */
  tagline?: string | null;
  /**
   * Landscape photo (at least 2000px wide) or a short muted MP4.
   */
  heroMedia: number | Media;
  /**
   * Only needed if the hero is a video. Shown while it loads and on devices that prefer less motion.
   */
  heroPoster?: (number | null) | Media;
  /**
   * Two or three sentences. Appears under the hero and in search results if no SEO description is set.
   */
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Shown as icons on the hotel page.
   */
  facilities?:
    | (
        | 'wifi'
        | 'parking'
        | 'restaurant'
        | 'bar'
        | 'breakfast'
        | 'garden'
        | 'dog-friendly'
        | 'family'
        | 'ev-charging'
        | 'accessible'
        | 'meetings'
        | 'weddings'
        | 'river'
        | 'self-checkin'
        | 'fireplace'
        | 'bikes'
        | 'walking'
        | 'fishing'
        | 'tea-coffee'
        | 'tv'
      )[]
    | null;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  layout?:
    | (
        | HeroBlock
        | TextBlock
        | TextWithImageBlock
        | GalleryBlock
        | RoomCardsBlock
        | FacilitiesBlock
        | MenusListBlock
        | EventsListBlock
        | OffersBlock
        | TestimonialsBlock
        | MapBlock
        | FAQBlock
        | CTABlock
        | NewsletterBlock
        | EnquiryFormBlock
        | EmbedBlock
        | HotelGridBlock
      )[]
    | null;
  address?: {
    line1?: string | null;
    line2?: string | null;
    town?: string | null;
    county?: string | null;
    postcode?: string | null;
  };
  phone?: string | null;
  /**
   * Contact form messages go here.
   */
  email?: string | null;
  map?: {
    lat?: number | null;
    lng?: number | null;
    /**
     * Used by the "Get directions" button. Paste the share link from Google Maps.
     */
    directionsUrl?: string | null;
  };
  /**
   * By car, by rail, parking notes.
   */
  directions?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  social?: {
    facebook?: string | null;
    instagram?: string | null;
    tripadvisor?: string | null;
    x?: string | null;
  };
  /**
   * The exact link guests use to book this hotel. Book Now buttons open it in a new tab. Leave blank to show the phone number and enquiry form instead.
   */
  bookingUrl?: string | null;
  /**
   * For restaurants that take online table bookings (e.g. ResDiary, Dojo). Adds a "Book a table" button to the hotel and dining pages.
   */
  tableBookingUrl?: string | null;
  checkIn?: string | null;
  checkOut?: string | null;
  /**
   * Shown to Google only.
   */
  priceRange?: ('£' | '££' | '£££') | null;
  hasWeddings?: boolean | null;
  weddingsIntro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  weddingsGallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  rooms?: {
    docs?: (number | Room)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  menus?: {
    docs?: (number | Menu)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  events?: {
    docs?: (number | Event)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  offers?: {
    docs?: (number | Offer)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * Leave blank to reuse the meta title.
     */
    ogTitle?: string | null;
    /**
     * Leave blank to reuse the meta description.
     */
    ogDescription?: string | null;
    twitterCard?: ('summary_large_image' | 'summary') | null;
    /**
     * Only needed if this page is a copy of a page elsewhere. Leave blank normally.
     */
    canonicalUrl?: string | null;
    noIndex?: boolean | null;
  };
  /**
   * Lower numbers show first on the Our Hotels page.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Photos, menu PDFs and short hero videos. Images are resized and converted automatically. Drag the dot on the preview to set the focal point.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * One short sentence for screen readers and Google, e.g. "Double bedroom with river views at The George". Required.
   */
  alt: string;
  caption?: string | null;
  createdBy?: (number | null) | User;
  blurhash?: string | null;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Admins see everything. Hotel Managers only see the hotels you assign to them.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'manager';
  hotels?: (number | Hotel)[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  /**
   * Leave blank on a hotel page to use the hotel hero.
   */
  media?: (number | null) | Media;
  poster?: (number | null) | Media;
  /**
   * Small line above the title, e.g. the location.
   */
  eyebrow?: string | null;
  /**
   * Leave blank on a hotel page to use the hotel name.
   */
  title?: string | null;
  subtitle?: string | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom' | 'book') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'hotels';
                value: number | Hotel;
              } | null);
          url?: string | null;
          bookHotel?: (number | null) | Hotel;
          label: string;
          /**
           * How the link looks.
           */
          appearance?: ('primary' | 'secondary') | null;
        };
        id?: string | null;
      }[]
    | null;
  height?: ('full' | 'tall' | 'short') | null;
  /**
   * Keeps text readable over the photo.
   */
  overlay?: ('gradient' | 'tint40' | 'tint50' | 'tint60') | null;
  showBookNow?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * Group pages such as Home, About, Contact, Careers and legal pages. Built from blocks.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Use "home" for the home page.
   */
  slug?: string | null;
  layout: (
    | HeroBlock
    | TextBlock
    | TextWithImageBlock
    | GalleryBlock
    | RoomCardsBlock
    | FacilitiesBlock
    | MenusListBlock
    | EventsListBlock
    | OffersBlock
    | TestimonialsBlock
    | MapBlock
    | FAQBlock
    | CTABlock
    | NewsletterBlock
    | EnquiryFormBlock
    | EmbedBlock
    | HotelGridBlock
  )[];
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * Leave blank to reuse the meta title.
     */
    ogTitle?: string | null;
    /**
     * Leave blank to reuse the meta description.
     */
    ogDescription?: string | null;
    twitterCard?: ('summary_large_image' | 'summary') | null;
    /**
     * Only needed if this page is a copy of a page elsewhere. Leave blank normally.
     */
    canonicalUrl?: string | null;
    noIndex?: boolean | null;
  };
  showInSitemap?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextBlock".
 */
export interface TextBlock {
  /**
   * Optional small heading above the text.
   */
  eyebrow?: string | null;
  richText: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  narrow?: boolean | null;
  style?: {
    tone?: ('cream' | 'sand' | 'linen' | 'charcoal') | null;
    spacing?: ('compact' | 'normal' | 'generous') | null;
    align?: ('left' | 'center') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'text';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextWithImageBlock".
 */
export interface TextWithImageBlock {
  image: number | Media;
  imagePosition?: ('left' | 'right') | null;
  eyebrow?: string | null;
  richText: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  links?:
    | {
        link: {
          type?: ('reference' | 'custom' | 'book') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'hotels';
                value: number | Hotel;
              } | null);
          url?: string | null;
          bookHotel?: (number | null) | Hotel;
          label: string;
          /**
           * How the link looks.
           */
          appearance?: ('primary' | 'secondary' | 'link') | null;
        };
        id?: string | null;
      }[]
    | null;
  style?: {
    tone?: ('cream' | 'sand' | 'linen' | 'charcoal') | null;
    spacing?: ('compact' | 'normal' | 'generous') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'textWithImage';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock".
 */
export interface GalleryBlock {
  heading?: string | null;
  source?: ('custom' | 'hotel') | null;
  images?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  layout?: ('masonry' | 'grid' | 'strip') | null;
  columns?: ('2' | '3' | '4') | null;
  style?: {
    tone?: ('cream' | 'sand' | 'linen' | 'charcoal') | null;
    spacing?: ('compact' | 'normal' | 'generous') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'gallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RoomCardsBlock".
 */
export interface RoomCardsBlock {
  heading?: string | null;
  intro?: string | null;
  source?: ('hotel' | 'custom') | null;
  /**
   * Only needed on a group page. Hotel pages use their own rooms.
   */
  hotel?: (number | null) | Hotel;
  rooms?: (number | Room)[] | null;
  style?: {
    tone?: ('cream' | 'sand' | 'linen' | 'charcoal') | null;
    spacing?: ('compact' | 'normal' | 'generous') | null;
    align?: ('left' | 'center') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'roomCards';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rooms".
 */
export interface Room {
  id: number;
  name: string;
  hotel: number | Hotel;
  /**
   * Part of the web address. Lower-case letters, numbers and dashes only.
   */
  slug?: string | null;
  sleeps?: number | null;
  /**
   * e.g. 6ft super-king
   */
  bedType?: string | null;
  /**
   * Optional
   */
  fromPrice?: number | null;
  /**
   * One or two sentences for the room card.
   */
  shortDescription?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  features?:
    | (
        | 'en-suite'
        | 'bath'
        | 'walk-in-shower'
        | 'king-bed'
        | 'super-king-bed'
        | 'twin-option'
        | 'sofa-bed'
        | 'dog-friendly'
        | 'ground-floor'
        | 'accessible'
        | 'view'
        | 'seating-area'
        | 'tea-coffee'
        | 'smart-tv'
        | 'wifi'
      )[]
    | null;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Overrides the hotel booking link for this room only.
   */
  bookingUrl?: string | null;
  /**
   * Lower numbers show first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FacilitiesBlock".
 */
export interface FacilitiesBlock {
  heading?: string | null;
  source?: ('hotel' | 'custom') | null;
  items?:
    | {
        icon:
          | 'wifi'
          | 'parking'
          | 'restaurant'
          | 'bar'
          | 'breakfast'
          | 'garden'
          | 'dog-friendly'
          | 'family'
          | 'ev-charging'
          | 'accessible'
          | 'meetings'
          | 'weddings'
          | 'river'
          | 'self-checkin'
          | 'fireplace'
          | 'bikes'
          | 'walking'
          | 'fishing'
          | 'tea-coffee'
          | 'tv';
        label: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  style?: {
    tone?: ('cream' | 'sand' | 'linen' | 'charcoal') | null;
    spacing?: ('compact' | 'normal' | 'generous') | null;
    align?: ('left' | 'center') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'facilities';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MenusListBlock".
 */
export interface MenusListBlock {
  heading?: string | null;
  intro?: string | null;
  /**
   * Only needed on a group page. Hotel pages show their own menus.
   */
  hotel?: (number | null) | Hotel;
  /**
   * Leave blank to show every current menu.
   */
  types?:
    | ('food' | 'drinks' | 'breakfast' | 'sunday' | 'afternoon-tea' | 'christmas' | 'specials' | 'children' | 'other')[]
    | null;
  style?: {
    tone?: ('cream' | 'sand' | 'linen' | 'charcoal') | null;
    spacing?: ('compact' | 'normal' | 'generous') | null;
    align?: ('left' | 'center') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'menusList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventsListBlock".
 */
export interface EventsListBlock {
  heading?: string | null;
  intro?: string | null;
  /**
   * Leave blank for every hotel. Hotel pages show their own events automatically.
   */
  hotel?: (number | null) | Hotel;
  /**
   * How many to show
   */
  limit?: number | null;
  style?: {
    tone?: ('cream' | 'sand' | 'linen' | 'charcoal') | null;
    spacing?: ('compact' | 'normal' | 'generous') | null;
    align?: ('left' | 'center') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'eventsList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OffersBlock".
 */
export interface OffersBlock {
  heading?: string | null;
  intro?: string | null;
  /**
   * Leave blank for group-wide and all hotels. Hotel pages show their own plus group-wide offers.
   */
  hotel?: (number | null) | Hotel;
  layout?: ('cards' | 'feature') | null;
  limit?: number | null;
  style?: {
    tone?: ('cream' | 'sand' | 'linen' | 'charcoal') | null;
    spacing?: ('compact' | 'normal' | 'generous') | null;
    align?: ('left' | 'center') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'offers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  heading?: string | null;
  source?: ('auto' | 'custom') | null;
  items?: (number | Testimonial)[] | null;
  limit?: number | null;
  style?: {
    tone?: ('cream' | 'sand' | 'linen' | 'charcoal') | null;
    spacing?: ('compact' | 'normal' | 'generous') | null;
    align?: ('left' | 'center') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * Short guest quotes shown in the Testimonials block.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  name: string;
  source?: ('google' | 'tripadvisor' | 'booking' | 'guestbook' | 'email') | null;
  /**
   * Admins: leave blank for a group-wide quote.
   */
  hotel?: (number | null) | Hotel;
  rating?: number | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MapBlock".
 */
export interface MapBlock {
  heading?: string | null;
  /**
   * Only needed on a group page. Hotel pages use their own pin and address.
   */
  hotel?: (number | null) | Hotel;
  showDirections?: boolean | null;
  style?: {
    tone?: ('cream' | 'sand' | 'linen' | 'charcoal') | null;
    spacing?: ('compact' | 'normal' | 'generous') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'map';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock".
 */
export interface FAQBlock {
  heading?: string | null;
  items?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  style?: {
    tone?: ('cream' | 'sand' | 'linen' | 'charcoal') | null;
    spacing?: ('compact' | 'normal' | 'generous') | null;
    align?: ('left' | 'center') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABlock".
 */
export interface CTABlock {
  title: string;
  text?: string | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom' | 'book') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'hotels';
                value: number | Hotel;
              } | null);
          url?: string | null;
          bookHotel?: (number | null) | Hotel;
          label: string;
          /**
           * How the link looks.
           */
          appearance?: ('primary' | 'secondary') | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. With an image the text sits on a brown tint for contrast.
   */
  backgroundImage?: (number | null) | Media;
  style?: {
    tone?: ('cream' | 'sand' | 'linen' | 'charcoal') | null;
    spacing?: ('compact' | 'normal' | 'generous') | null;
    align?: ('left' | 'center') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsletterBlock".
 */
export interface NewsletterBlock {
  heading?: string | null;
  text?: string | null;
  consentText?: string | null;
  style?: {
    tone?: ('cream' | 'sand' | 'linen' | 'charcoal') | null;
    spacing?: ('compact' | 'normal' | 'generous') | null;
    align?: ('left' | 'center') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'newsletter';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EnquiryFormBlock".
 */
export interface EnquiryFormBlock {
  heading?: string | null;
  intro?: string | null;
  /**
   * Messages go to this hotel. Leave blank on a group page to let the visitor choose. Hotel pages use their own.
   */
  hotel?: (number | null) | Hotel;
  showStayFields?: boolean | null;
  style?: {
    tone?: ('cream' | 'sand' | 'linen' | 'charcoal') | null;
    spacing?: ('compact' | 'normal' | 'generous') | null;
    align?: ('left' | 'center') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'enquiryForm';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EmbedBlock".
 */
export interface EmbedBlock {
  heading?: string | null;
  provider: 'youtube' | 'vimeo' | 'google-maps' | 'other';
  /**
   * Paste the normal share link, e.g. https://www.youtube.com/watch?v=... or a Google Maps embed link.
   */
  url: string;
  /**
   * Short description for screen readers.
   */
  title: string;
  aspect?: ('16:9' | '4:3' | '1:1') | null;
  style?: {
    tone?: ('cream' | 'sand' | 'linen' | 'charcoal') | null;
    spacing?: ('compact' | 'normal' | 'generous') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'embed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HotelGridBlock".
 */
export interface HotelGridBlock {
  heading?: string | null;
  intro?: string | null;
  /**
   * Leave blank to show every hotel in display order.
   */
  hotels?: (number | Hotel)[] | null;
  layout?: ('grid' | 'rows') | null;
  style?: {
    tone?: ('cream' | 'sand' | 'linen' | 'charcoal') | null;
    spacing?: ('compact' | 'normal' | 'generous') | null;
    align?: ('left' | 'center') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'hotelGrid';
}
/**
 * Upload a PDF or type the menu in. Set a "valid to" date and the menu disappears from the website on its own.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus".
 */
export interface Menu {
  id: number;
  /**
   * e.g. "Autumn à la carte"
   */
  title: string;
  hotel: number | Hotel;
  type: 'food' | 'drinks' | 'breakfast' | 'sunday' | 'afternoon-tea' | 'christmas' | 'specials' | 'children' | 'other';
  validFrom?: string | null;
  /**
   * The menu is hidden after this day. Leave blank to show indefinitely.
   */
  validTo?: string | null;
  format: 'pdf' | 'structured';
  pdf?: (number | null) | Media;
  /**
   * e.g. serving times, allergen note, "menu changes weekly".
   */
  note?: string | null;
  sections?:
    | {
        /**
         * e.g. Starters
         */
        title: string;
        description?: string | null;
        items?:
          | {
              name: string;
              /**
               * e.g. 14.50
               */
              price?: string | null;
              description?: string | null;
              dietary?: {
                v?: boolean | null;
                vg?: boolean | null;
                gf?: boolean | null;
                df?: boolean | null;
                n?: boolean | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Past events drop off the website automatically the day after they end.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  hotel: number | Hotel;
  start: string;
  end?: string | null;
  image?: (number | null) | Media;
  /**
   * One or two sentences shown on the event card.
   */
  summary: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * e.g. "£45 per person" or "Free"
   */
  price?: string | null;
  ticketUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Offers show between their start and end dates, then disappear on their own.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers".
 */
export interface Offer {
  id: number;
  title: string;
  /**
   * Admins: leave blank for a group-wide offer.
   */
  hotel?: (number | null) | Hotel;
  image: number | Media;
  /**
   * The headline deal in one or two sentences.
   */
  summary: string;
  terms?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  startDate?: string | null;
  endDate: string;
  promoCode?: string | null;
  /**
   * Leave blank to use the hotel booking link.
   */
  linkUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Every contact form message is kept here as well as being emailed, so nothing is lost if an email goes astray.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  subject?: ('stay' | 'dining' | 'event' | 'wedding' | 'other') | null;
  arrival?: string | null;
  departure?: string | null;
  guests?: number | null;
  message: string;
  hotel?: (number | null) | Hotel;
  status?: ('new' | 'replied' | 'closed') | null;
  notes?: string | null;
  sourcePath?: string | null;
  emailSent?: boolean | null;
  autoReplySent?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * The old path, starting with a slash and without the domain, e.g. /grassington-lodge/rooms/room-six/
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'hotels';
          value: number | Hotel;
        } | null);
    url?: string | null;
  };
  type: '301' | '302';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'hotels';
        value: number | Hotel;
      } | null)
    | ({
        relationTo: 'rooms';
        value: number | Room;
      } | null)
    | ({
        relationTo: 'menus';
        value: number | Menu;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'offers';
        value: number | Offer;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hotels_select".
 */
export interface HotelsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  location?: T;
  tagline?: T;
  heroMedia?: T;
  heroPoster?: T;
  intro?: T;
  facilities?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        text?: T | TextBlockSelect<T>;
        textWithImage?: T | TextWithImageBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        roomCards?: T | RoomCardsBlockSelect<T>;
        facilities?: T | FacilitiesBlockSelect<T>;
        menusList?: T | MenusListBlockSelect<T>;
        eventsList?: T | EventsListBlockSelect<T>;
        offers?: T | OffersBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        map?: T | MapBlockSelect<T>;
        faq?: T | FAQBlockSelect<T>;
        cta?: T | CTABlockSelect<T>;
        newsletter?: T | NewsletterBlockSelect<T>;
        enquiryForm?: T | EnquiryFormBlockSelect<T>;
        embed?: T | EmbedBlockSelect<T>;
        hotelGrid?: T | HotelGridBlockSelect<T>;
      };
  address?:
    | T
    | {
        line1?: T;
        line2?: T;
        town?: T;
        county?: T;
        postcode?: T;
      };
  phone?: T;
  email?: T;
  map?:
    | T
    | {
        lat?: T;
        lng?: T;
        directionsUrl?: T;
      };
  directions?: T;
  social?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        tripadvisor?: T;
        x?: T;
      };
  bookingUrl?: T;
  tableBookingUrl?: T;
  checkIn?: T;
  checkOut?: T;
  priceRange?: T;
  hasWeddings?: T;
  weddingsIntro?: T;
  weddingsGallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  rooms?: T;
  menus?: T;
  events?: T;
  offers?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        ogTitle?: T;
        ogDescription?: T;
        twitterCard?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  media?: T;
  poster?: T;
  eyebrow?: T;
  title?: T;
  subtitle?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              bookHotel?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  height?: T;
  overlay?: T;
  showBookNow?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextBlock_select".
 */
export interface TextBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  richText?: T;
  narrow?: T;
  style?:
    | T
    | {
        tone?: T;
        spacing?: T;
        align?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextWithImageBlock_select".
 */
export interface TextWithImageBlockSelect<T extends boolean = true> {
  image?: T;
  imagePosition?: T;
  eyebrow?: T;
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              bookHotel?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  style?:
    | T
    | {
        tone?: T;
        spacing?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock_select".
 */
export interface GalleryBlockSelect<T extends boolean = true> {
  heading?: T;
  source?: T;
  images?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  layout?: T;
  columns?: T;
  style?:
    | T
    | {
        tone?: T;
        spacing?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RoomCardsBlock_select".
 */
export interface RoomCardsBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  source?: T;
  hotel?: T;
  rooms?: T;
  style?:
    | T
    | {
        tone?: T;
        spacing?: T;
        align?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FacilitiesBlock_select".
 */
export interface FacilitiesBlockSelect<T extends boolean = true> {
  heading?: T;
  source?: T;
  items?:
    | T
    | {
        icon?: T;
        label?: T;
        description?: T;
        id?: T;
      };
  style?:
    | T
    | {
        tone?: T;
        spacing?: T;
        align?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MenusListBlock_select".
 */
export interface MenusListBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  hotel?: T;
  types?: T;
  style?:
    | T
    | {
        tone?: T;
        spacing?: T;
        align?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventsListBlock_select".
 */
export interface EventsListBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  hotel?: T;
  limit?: T;
  style?:
    | T
    | {
        tone?: T;
        spacing?: T;
        align?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OffersBlock_select".
 */
export interface OffersBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  hotel?: T;
  layout?: T;
  limit?: T;
  style?:
    | T
    | {
        tone?: T;
        spacing?: T;
        align?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock_select".
 */
export interface TestimonialsBlockSelect<T extends boolean = true> {
  heading?: T;
  source?: T;
  items?: T;
  limit?: T;
  style?:
    | T
    | {
        tone?: T;
        spacing?: T;
        align?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MapBlock_select".
 */
export interface MapBlockSelect<T extends boolean = true> {
  heading?: T;
  hotel?: T;
  showDirections?: T;
  style?:
    | T
    | {
        tone?: T;
        spacing?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock_select".
 */
export interface FAQBlockSelect<T extends boolean = true> {
  heading?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  style?:
    | T
    | {
        tone?: T;
        spacing?: T;
        align?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABlock_select".
 */
export interface CTABlockSelect<T extends boolean = true> {
  title?: T;
  text?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              bookHotel?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  backgroundImage?: T;
  style?:
    | T
    | {
        tone?: T;
        spacing?: T;
        align?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsletterBlock_select".
 */
export interface NewsletterBlockSelect<T extends boolean = true> {
  heading?: T;
  text?: T;
  consentText?: T;
  style?:
    | T
    | {
        tone?: T;
        spacing?: T;
        align?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EnquiryFormBlock_select".
 */
export interface EnquiryFormBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  hotel?: T;
  showStayFields?: T;
  style?:
    | T
    | {
        tone?: T;
        spacing?: T;
        align?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EmbedBlock_select".
 */
export interface EmbedBlockSelect<T extends boolean = true> {
  heading?: T;
  provider?: T;
  url?: T;
  title?: T;
  aspect?: T;
  style?:
    | T
    | {
        tone?: T;
        spacing?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HotelGridBlock_select".
 */
export interface HotelGridBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  hotels?: T;
  layout?: T;
  style?:
    | T
    | {
        tone?: T;
        spacing?: T;
        align?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rooms_select".
 */
export interface RoomsSelect<T extends boolean = true> {
  name?: T;
  hotel?: T;
  slug?: T;
  sleeps?: T;
  bedType?: T;
  fromPrice?: T;
  shortDescription?: T;
  description?: T;
  features?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  bookingUrl?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus_select".
 */
export interface MenusSelect<T extends boolean = true> {
  title?: T;
  hotel?: T;
  type?: T;
  validFrom?: T;
  validTo?: T;
  format?: T;
  pdf?: T;
  note?: T;
  sections?:
    | T
    | {
        title?: T;
        description?: T;
        items?:
          | T
          | {
              name?: T;
              price?: T;
              description?: T;
              dietary?:
                | T
                | {
                    v?: T;
                    vg?: T;
                    gf?: T;
                    df?: T;
                    n?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  hotel?: T;
  start?: T;
  end?: T;
  image?: T;
  summary?: T;
  description?: T;
  price?: T;
  ticketUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers_select".
 */
export interface OffersSelect<T extends boolean = true> {
  title?: T;
  hotel?: T;
  image?: T;
  summary?: T;
  terms?: T;
  startDate?: T;
  endDate?: T;
  promoCode?: T;
  linkUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        text?: T | TextBlockSelect<T>;
        textWithImage?: T | TextWithImageBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        roomCards?: T | RoomCardsBlockSelect<T>;
        facilities?: T | FacilitiesBlockSelect<T>;
        menusList?: T | MenusListBlockSelect<T>;
        eventsList?: T | EventsListBlockSelect<T>;
        offers?: T | OffersBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        map?: T | MapBlockSelect<T>;
        faq?: T | FAQBlockSelect<T>;
        cta?: T | CTABlockSelect<T>;
        newsletter?: T | NewsletterBlockSelect<T>;
        enquiryForm?: T | EnquiryFormBlockSelect<T>;
        embed?: T | EmbedBlockSelect<T>;
        hotelGrid?: T | HotelGridBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        ogTitle?: T;
        ogDescription?: T;
        twitterCard?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  showInSitemap?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  createdBy?: T;
  blurhash?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  name?: T;
  source?: T;
  hotel?: T;
  rating?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  subject?: T;
  arrival?: T;
  departure?: T;
  guests?: T;
  message?: T;
  hotel?: T;
  status?: T;
  notes?: T;
  sourcePath?: T;
  emailSent?: T;
  autoReplySent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  hotels?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline?: string | null;
  logo?: (number | null) | Media;
  logoLight?: (number | null) | Media;
  seo?: {
    /**
     * Added after every page title, e.g. "Rooms | The Castle | GR Hotels".
     */
    titleSuffix?: string | null;
    defaultDescription?: string | null;
    defaultImage?: (number | null) | Media;
    /**
     * Without the @
     */
    twitterHandle?: string | null;
  };
  contact?: {
    phone?: string | null;
    email?: string | null;
    address?: string | null;
    /**
     * e.g. "GR Hotels Ltd, registered in England No. 00000000"
     */
    companyLine?: string | null;
  };
  social?: {
    facebook?: string | null;
    instagram?: string | null;
    linkedin?: string | null;
    x?: string | null;
  };
  enquiries?: {
    /**
     * Receives messages from group pages, and from any hotel that has no enquiry email of its own.
     */
    fallbackEmail?: string | null;
    /**
     * Optional. Every enquiry from every hotel is also sent here.
     */
    copyTo?: string | null;
    autoReply?: boolean | null;
    autoReplySubject?: string | null;
    /**
     * Plain text. {name}, {hotel} and {phone} are filled in automatically. {hotel} becomes the site name for group enquiries.
     */
    autoReplyMessage?: string | null;
  };
  booking?: {
    pickerTitle?: string | null;
    pickerIntro?: string | null;
    utmSource?: string | null;
    utmMedium?: string | null;
  };
  cookies?: {
    title?: string | null;
    text?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Our Hotels is always shown and lists every hotel automatically.
   */
  header?:
    | {
        link: {
          type?: ('reference' | 'custom' | 'book') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'hotels';
                value: number | Hotel;
              } | null);
          url?: string | null;
          bookHotel?: (number | null) | Hotel;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  footerColumns?:
    | {
        title: string;
        links?:
          | {
              link: {
                type?: ('reference' | 'custom' | 'book') | null;
                newTab?: boolean | null;
                reference?:
                  | ({
                      relationTo: 'pages';
                      value: number | Page;
                    } | null)
                  | ({
                      relationTo: 'hotels';
                      value: number | Hotel;
                    } | null);
                url?: string | null;
                bookHotel?: (number | null) | Hotel;
                label: string;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  legalLinks?:
    | {
        link: {
          type?: ('reference' | 'custom' | 'book') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'hotels';
                value: number | Hotel;
              } | null);
          url?: string | null;
          bookHotel?: (number | null) | Hotel;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * A sentence about the group.
   */
  footerNote?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * A thin strip above the header for time-limited news.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcement-bar".
 */
export interface AnnouncementBar {
  id: number;
  enabled?: boolean | null;
  text?: string | null;
  hasLink?: boolean | null;
  link?: {
    type?: ('reference' | 'custom' | 'book') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'hotels';
          value: number | Hotel;
        } | null);
    url?: string | null;
    bookHotel?: (number | null) | Hotel;
    label: string;
  };
  startDate?: string | null;
  endDate?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  logo?: T;
  logoLight?: T;
  seo?:
    | T
    | {
        titleSuffix?: T;
        defaultDescription?: T;
        defaultImage?: T;
        twitterHandle?: T;
      };
  contact?:
    | T
    | {
        phone?: T;
        email?: T;
        address?: T;
        companyLine?: T;
      };
  social?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        linkedin?: T;
        x?: T;
      };
  enquiries?:
    | T
    | {
        fallbackEmail?: T;
        copyTo?: T;
        autoReply?: T;
        autoReplySubject?: T;
        autoReplyMessage?: T;
      };
  booking?:
    | T
    | {
        pickerTitle?: T;
        pickerIntro?: T;
        utmSource?: T;
        utmMedium?: T;
      };
  cookies?:
    | T
    | {
        title?: T;
        text?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  header?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              bookHotel?: T;
              label?: T;
            };
        id?: T;
      };
  footerColumns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    bookHotel?: T;
                    label?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  legalLinks?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              bookHotel?: T;
              label?: T;
            };
        id?: T;
      };
  footerNote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcement-bar_select".
 */
export interface AnnouncementBarSelect<T extends boolean = true> {
  enabled?: T;
  text?: T;
  hasLink?: T;
  link?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        bookHotel?: T;
        label?: T;
      };
  startDate?: T;
  endDate?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'hotels';
          value: number | Hotel;
        } | null)
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null);
    global?: string | null;
    user?: {
      relationTo: 'users';
      value: number | User;
    } | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}